server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: auth-service
  cloud:
    azure:
      credential:
        managed-identity-enabled: true
        client-id: ${AZURE_MANAGED_IDENTITY_CLIENT_ID:}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6380}
      timeout: 2000ms

app:
  datasource:
    azure-sql:
      url: ${AZURE_SQL_JDBC_URL}
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      hikari:
        pool-name: AuthAzureSqlPool
        maximum-pool-size: 15
        minimum-idle: 5
        connection-timeout: 10000
        idle-timeout: 300000
  security:
    jwt-secret: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
    jwt-expiration-ms: 86400000 # 24 Hours

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
