-- Run against the application's Azure SQL database after schema-azure-sql.sql.
-- Restores the three original demo customers and five opening balances.
-- Demo password: password123 (BCrypt). Contact details are synthetic.
-- Existing customers, passwords, accounts and balances are left unchanged.
-- Accounts are created only for customers inserted by this run; safe to rerun.
-- No transaction/outbox events are generated by this opening-balance fixture.
SET XACT_ABORT ON;
SET NOCOUNT ON;

BEGIN TRY
    BEGIN TRANSACTION;

    DECLARE @new_customers TABLE (customer_id BIGINT, username NVARCHAR(50));
    DECLARE @password_hash NVARCHAR(255) = N'$2a$10$rUxZUS7mrNY.MaP7WtGdfuHM2aaNt37ntfZbVAmUuq/MgtVrhO0Jm';

    INSERT INTO dbo.CUSTOMER
        (username, password_hash, first_name, last_name, email, contact_no, status)
    OUTPUT inserted.customer_id, inserted.username INTO @new_customers
    SELECT seed.username, @password_hash, seed.first_name, seed.last_name,
           seed.email, seed.contact_no, N'ACTIVE'
    FROM (VALUES
        (N'lviernes', N'Levi', N'Viernes', N'lviernes@example.test', N'+630000000001'),
        (N'arosales', N'Aly', N'Rosales', N'arosales@example.test', N'+630000000002'),
        (N'glim', N'Gill', N'Lim', N'glim@example.test', N'+630000000003')
    ) AS seed(username, first_name, last_name, email, contact_no)
    WHERE NOT EXISTS (
        SELECT 1 FROM dbo.CUSTOMER WITH (UPDLOCK, HOLDLOCK)
        WHERE username = seed.username
    );

    -- Account numbers use BankingIdentifiers' current prefix and Luhn checksum.
    -- Resolve customer IDs from the inserted rows, never assume IDs 1, 2 or 3.
    INSERT INTO dbo.ACCOUNT
        (customer_id, account_number, account_type, currency, current_balance, status)
    SELECT customer.customer_id, seed.account_number, seed.account_type,
           N'PHP', seed.opening_balance, N'ACTIVE'
    FROM (VALUES
        (N'lviernes', N'001181233469', N'SAVINGS_ACCOUNT',     125450.0000),
        (N'lviernes', N'001381233467', N'CHECKING_ACCOUNT',     50000.0000),
        (N'lviernes', N'001981233461', N'STRESS_TEST_ACCOUNT',     60.0000),
        (N'arosales', N'001133218709', N'SAVINGS_ACCOUNT',      84320.5000),
        (N'glim',     N'001428928483', N'TIME_DEPOSIT',        350000.0000)
    ) AS seed(username, account_number, account_type, opening_balance)
    JOIN @new_customers AS customer ON customer.username = seed.username;

    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
    THROW;
END CATCH;
GO

-- ----------------------------------------------------------------------------
-- Phase 6 Loans. Requires scripts/migrate_phase6_loans.sql to have run first.
-- Safe to rerun.
-- ----------------------------------------------------------------------------

-- Hardcoded credit scores (like a value received from a credit bureau) and incomes.
UPDATE dbo.CUSTOMER SET credit_score = 520, monthly_income = 20000.0000  WHERE username = N'lviernes';  -- LOW band
UPDATE dbo.CUSTOMER SET credit_score = 670, monthly_income = 45000.0000  WHERE username = N'arosales';  -- NORMAL band
UPDATE dbo.CUSTOMER SET credit_score = 800, monthly_income = 150000.0000 WHERE username = N'glim';      -- HIGH band
GO

-- The bank's own loan account: holds the money PayPink lends out.
-- paypink_bank cannot log in: its password hash is not a valid BCrypt hash.
SET XACT_ABORT ON;
BEGIN TRY
    BEGIN TRANSACTION;

    IF NOT EXISTS (SELECT 1 FROM dbo.CUSTOMER WITH (UPDLOCK, HOLDLOCK) WHERE username = N'paypink_bank')
        INSERT INTO dbo.CUSTOMER (username, password_hash, first_name, last_name, email, contact_no, status, credit_score, monthly_income)
        VALUES (N'paypink_bank', N'!no-login', N'PayPink', N'Bank', N'loans@paypink.example.test', N'+630000000000', N'ACTIVE', 850, 0);

    IF NOT EXISTS (SELECT 1 FROM dbo.ACCOUNT WITH (UPDLOCK, HOLDLOCK) WHERE account_number = N'PH1000000LOAN')
        INSERT INTO dbo.ACCOUNT (customer_id, account_number, account_type, currency, current_balance, status)
        SELECT customer_id, N'PH1000000LOAN', N'INTERNAL', N'PHP', 50000000.0000, N'ACTIVE'
        FROM dbo.CUSTOMER WHERE username = N'paypink_bank';

    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
    THROW;
END CATCH;
