-- Run against the application's Azure SQL database after schema-azure-sql.sql.
-- Restores the three original demo customers and five opening balances.
-- Demo password: password123 (BCrypt). Contact details are synthetic.
-- Existing customers, passwords, accounts and balances are left unchanged.
-- Accounts are created only for customers inserted by this run; safe to rerun.
-- No transaction/outbox events are generated by this opening-balance fixture.
SET XACT_ABORT ON;
SET NOCOUNT ON;

BEGIN TRY
    BEGIN TRANSACTION;

    DECLARE @new_customers TABLE (customer_id BIGINT, username NVARCHAR(50));
    DECLARE @password_hash NVARCHAR(255) = N'$2a$10$rUxZUS7mrNY.MaP7WtGdfuHM2aaNt37ntfZbVAmUuq/MgtVrhO0Jm';

    INSERT INTO dbo.CUSTOMER
        (username, password_hash, first_name, last_name, email, contact_no, status)
    OUTPUT inserted.customer_id, inserted.username INTO @new_customers
    SELECT seed.username, @password_hash, seed.first_name, seed.last_name,
           seed.email, seed.contact_no, N'ACTIVE'
    FROM (VALUES
        (N'lviernes', N'Levi', N'Viernes', N'lviernes@example.test', N'+630000000001'),
        (N'arosales', N'Aly', N'Rosales', N'arosales@example.test', N'+630000000002'),
        (N'glim', N'Gill', N'Lim', N'glim@example.test', N'+630000000003')
    ) AS seed(username, first_name, last_name, email, contact_no)
    WHERE NOT EXISTS (
        SELECT 1 FROM dbo.CUSTOMER WITH (UPDLOCK, HOLDLOCK)
        WHERE username = seed.username
    );

    -- Account numbers use BankingIdentifiers' current prefix and Luhn checksum.
    -- Resolve customer IDs from the inserted rows, never assume IDs 1, 2 or 3.
    INSERT INTO dbo.ACCOUNT
        (customer_id, account_number, account_type, currency, current_balance, status)
    SELECT customer.customer_id, seed.account_number, seed.account_type,
           N'PHP', seed.opening_balance, N'ACTIVE'
    FROM (VALUES
        (N'lviernes', N'001181233469', N'SAVINGS_ACCOUNT',     125450.0000),
        (N'lviernes', N'001381233467', N'CHECKING_ACCOUNT',     50000.0000),
        (N'lviernes', N'001981233461', N'STRESS_TEST_ACCOUNT',     60.0000),
        (N'arosales', N'001133218709', N'SAVINGS_ACCOUNT',      84320.5000),
        (N'glim',     N'001428928483', N'TIME_DEPOSIT',        350000.0000)
    ) AS seed(username, account_number, account_type, opening_balance)
    JOIN @new_customers AS customer ON customer.username = seed.username;

    -- Ensure legacy aliases are in AUDIT_LOG for backward compatibility
    INSERT INTO dbo.AUDIT_LOG (customer_id, action, entity, details)
    SELECT a.customer_id, N'ACCOUNT_RENUMBERED', CONCAT(N'ACCOUNT:', a.account_id), legacy.old_number
    FROM (VALUES
        (N'001181233469', N'ACC-PH-1001-8842'),
        (N'001381233467', N'ACC-PH-1001-9921'),
        (N'001981233461', N'ACC-PH-1001-7714'),
        (N'001133218709', N'ACC-PH-2002-3311'),
        (N'001428928483', N'ACC-PH-3003-4422')
    ) AS legacy(account_number, old_number)
    JOIN dbo.ACCOUNT a ON a.account_number = legacy.account_number
    WHERE NOT EXISTS (
        SELECT 1 FROM dbo.AUDIT_LOG l WHERE l.action = N'ACCOUNT_RENUMBERED' AND l.details = legacy.old_number
    );

    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
    THROW;
END CATCH;
