package com.bank.t24.savings;
import com.bank.t24.model.Account;
import com.bank.t24.repository.AccountRepository;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.transaction.annotation.*;
import org.springframework.web.server.ResponseStatusException;
import java.math.BigDecimal;
import java.util.*;
import java.util.concurrent.*;
import static org.assertj.core.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;

@DataJpaTest(properties="spring.jpa.show-sql=false")
@AutoConfigureTestDatabase(replace=AutoConfigureTestDatabase.Replace.NONE)
 @Import({CoreSavingsService.class,ObjectMapper.class,com.bank.t24.service.T24PostingService.class,com.bank.t24.service.T24HoldService.class})
@Transactional(propagation=Propagation.NOT_SUPPORTED)
class CoreSavingsServiceTest {
 @Autowired CoreSavingsService service;
 @Autowired com.bank.t24.service.T24PostingService posting;
 @Autowired com.bank.t24.service.T24HoldService holds;
 @Autowired AccountRepository accounts;
 @Autowired JdbcTemplate jdbc;
 @MockBean SavingsRiskClient risk;
 Long account;
 UUID goal;
 @BeforeEach void setup() {
  jdbc.execute("CREATE SCHEMA IF NOT EXISTS app");
  jdbc.execute("CREATE TABLE IF NOT EXISTS t24.SAVINGS_RESERVATION(goal_id VARCHAR(36) PRIMARY KEY,account_id BIGINT,reserved_amount DECIMAL(18,2))");
  jdbc.execute("CREATE TABLE IF NOT EXISTS t24.SAVINGS_OPERATION(operation_id VARCHAR(36) PRIMARY KEY,account_id BIGINT,request_json VARCHAR,result_json VARCHAR,risk_score DECIMAL(6,5),created_at TIMESTAMP)");
  jdbc.execute("CREATE TABLE IF NOT EXISTS app.OUTBOX_EVENT(event_id BIGINT GENERATED BY DEFAULT AS IDENTITY,aggregate_id VARCHAR(40),event_type VARCHAR(50),payload VARCHAR,status VARCHAR(20),created_date TIMESTAMP)");
  Account a=new Account();a.setCustomerId(10L);a.setAccountNumber(UUID.randomUUID().toString().substring(0,20));a.setAccountType("SAVINGS_ACCOUNT");a.setCurrentBalance(new BigDecimal("15000"));a.setHeldBalance(new BigDecimal("1000"));account=accounts.saveAndFlush(a).getAccountId();goal=UUID.randomUUID();
  when(risk.approve(any(),any(),any())).thenReturn(new BigDecimal("0.10"));
 }
 SavingsCommand command(UUID id,String type,String amount) {return new SavingsCommand(id,10L,account,type,List.of(new SavingsCommand.Line(goal,new BigDecimal(amount),new BigDecimal("10000"))));}
 BigDecimal held(){return accounts.findById(account).orElseThrow().getHeldBalance();}
 @Test void staleHeldTotalStillDeductsReservationsAndProtectsTransfers() {
  jdbc.update("UPDATE t24.ACCOUNT SET current_balance=129014.59,held_balance=0 WHERE account_id=?",account);
  UUID circle=UUID.randomUUID();
  jdbc.update("INSERT INTO t24.SAVINGS_RESERVATION VALUES(?,?,20600)",goal.toString(),account);
  jdbc.update("INSERT INTO t24.SAVINGS_RESERVATION VALUES(?,?,500)",circle.toString(),account);
  assertThat(service.funding(account,goal.toString()).get("availableBalance")).isEqualByComparingTo("107914.59");
  assertThat(service.funding(account,goal.toString()).get("reservedSavings")).isEqualByComparingTo("21100");
  var hold=new com.bank.t24.dto.T24HoldRequest(account,null,new BigDecimal("107914.60"),"PHP",UUID.randomUUID().toString());
  assertThatThrownBy(()->holds.placeHold(hold)).isInstanceOf(IllegalStateException.class).hasMessageContaining("Insufficient funds");
  var receiver=new Account();receiver.setAccountNumber("recv"+UUID.randomUUID().toString().substring(0,8));receiver.setCustomerId(11L);receiver.setAccountType("SAVINGS_ACCOUNT");receiver.setCurrentBalance(BigDecimal.ZERO);accounts.saveAndFlush(receiver);
  String source=accounts.findById(account).orElseThrow().getAccountNumber();
  var denied=posting.executeDoubleEntryPosting(UUID.randomUUID().toString(),source,receiver.getAccountNumber(),new BigDecimal("107914.60"),"PHP","stale-held-test");
  assertThat(denied.success()).isFalse();
  assertThat(accounts.findById(account).orElseThrow().getCurrentBalance()).isEqualByComparingTo("129014.59");
  // Release must also tolerate a stale aggregate without losing the other goal.
  jdbc.update("UPDATE t24.ACCOUNT SET held_balance=0 WHERE account_id=?",account);
  service.apply(new SavingsCommand(UUID.randomUUID(),10L,account,"RELEASE",List.of(new SavingsCommand.Line(goal,new BigDecimal("20600"),new BigDecimal("30000")))));
  assertThat(held()).isEqualByComparingTo("500");
  assertThat(service.funding(account,circle.toString()).get("availableBalance")).isEqualByComparingTo("128514.59");
 }
 @Test void reservedGoalsCannotBeSpentUntilReleased() {
  service.apply(command(UUID.randomUUID(),"ALLOCATE","3000.00"));
  UUID circleGoal=UUID.randomUUID();
  service.apply(new SavingsCommand(UUID.randomUUID(),10L,account,"ALLOCATE",List.of(new SavingsCommand.Line(circleGoal,new BigDecimal("2000"),new BigDecimal("10000")))));
  var receiver=new Account();receiver.setAccountNumber("recv"+UUID.randomUUID().toString().substring(0,8));receiver.setCustomerId(11L);receiver.setAccountType("SAVINGS_ACCOUNT");receiver.setStatus("ACTIVE");receiver.setCurrency("PHP");receiver.setCurrentBalance(BigDecimal.ZERO);receiver.setHeldBalance(BigDecimal.ZERO);accounts.saveAndFlush(receiver);
  String source=accounts.findById(account).orElseThrow().getAccountNumber();
  var denied=posting.executeDoubleEntryPosting(UUID.randomUUID().toString(),source,receiver.getAccountNumber(),new BigDecimal("10000"),"PHP","test-ft");
  assertThat(denied.success()).isFalse();assertThat(denied.errorMessage()).contains("Insufficient available");
  var snapshot=service.breakdown(account);
  assertThat((Map<?,?>)snapshot.get("reservations")).hasSize(2);
  service.apply(new SavingsCommand(UUID.randomUUID(),10L,account,"RELEASE",List.of(new SavingsCommand.Line(circleGoal,new BigDecimal("2000"),new BigDecimal("10000")))));
  var allowed=posting.executeDoubleEntryPosting(UUID.randomUUID().toString(),source,receiver.getAccountNumber(),new BigDecimal("10000"),"PHP","test-ft-2");
  assertThat(allowed.success()).isTrue();
  assertThat(held()).isEqualByComparingTo("4000");
  assertThat(service.balances(account).get(goal.toString())).isEqualByComparingTo("3000");
 }
 @Test void allocationReleaseAndRetryKeepAccountBalance() {
  UUID id=UUID.randomUUID();service.apply(command(id,"ALLOCATE","3000.00"));service.apply(command(id,"ALLOCATE","3000.00"));
  assertThat(held()).isEqualByComparingTo("4000");assertThat(accounts.findById(account).orElseThrow().getCurrentBalance()).isEqualByComparingTo("15000");
  service.apply(command(UUID.randomUUID(),"RELEASE","500.00"));assertThat(held()).isEqualByComparingTo("3500");assertThat(service.balances(account).get(goal.toString())).isEqualByComparingTo("2500");
  assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM app.OUTBOX_EVENT WHERE aggregate_id=?",Integer.class,id.toString())).isEqualTo(1);
 }
 @Test void fundingSubtractsAllGoalReservationsAndOtherHolds() {
  service.apply(command(UUID.randomUUID(),"ALLOCATE","3000.00"));
  UUID other=UUID.randomUUID();
  service.apply(new SavingsCommand(UUID.randomUUID(),10L,account,"ALLOCATE",List.of(new SavingsCommand.Line(other,new BigDecimal("2000.00"),new BigDecimal("10000")))));
  var funds=service.funding(account,goal.toString());
  assertThat(funds.get("accountBalance")).isEqualByComparingTo("15000");
  assertThat(funds.get("reservedSavings")).isEqualByComparingTo("5000");
  assertThat(funds.get("otherHolds")).isEqualByComparingTo("1000");
  assertThat(funds.get("availableBalance")).isEqualByComparingTo("9000");
  assertThat(funds.get("goalSavedAmount")).isEqualByComparingTo("3000");
  assertThatThrownBy(()->service.apply(new SavingsCommand(UUID.randomUUID(),10L,account,"ALLOCATE",List.of(new SavingsCommand.Line(UUID.randomUUID(),new BigDecimal("9000.01"),new BigDecimal("20000")))))).isInstanceOf(ResponseStatusException.class);
  assertThat(service.funding(account,goal.toString()).get("availableBalance")).isEqualByComparingTo("9000");
 }
 @Test void conflictingRetryAndForeignOwnerFail() {
  UUID id=UUID.randomUUID();service.apply(command(id,"ALLOCATE","100.00"));
  assertThatThrownBy(()->service.apply(command(id,"ALLOCATE","200.00"))).isInstanceOf(ResponseStatusException.class);
  assertThatThrownBy(()->service.apply(new SavingsCommand(UUID.randomUUID(),11L,account,"ALLOCATE",command(id,"ALLOCATE","100.00").lines()))).isInstanceOf(ResponseStatusException.class);
  assertThat(held()).isEqualByComparingTo("1100");
 }
 @Test void insufficientSplitIsAtomic() {
  var lines=List.of(new SavingsCommand.Line(goal,new BigDecimal("9000.00"),new BigDecimal("10000")),new SavingsCommand.Line(UUID.randomUUID(),new BigDecimal("6000.00"),new BigDecimal("10000")));
  assertThatThrownBy(()->service.apply(new SavingsCommand(UUID.randomUUID(),10L,account,"ALLOCATE",lines))).isInstanceOf(ResponseStatusException.class);
  assertThat(held()).isEqualByComparingTo("1000");assertThat(service.balances(account)).isEmpty();verifyNoInteractions(risk);
 }
 @Test void failedRiskDoesNotTouchFunds() {
  when(risk.approve(any(),any(),any())).thenThrow(new ResponseStatusException(org.springframework.http.HttpStatus.SERVICE_UNAVAILABLE));
  assertThatThrownBy(()->service.apply(command(UUID.randomUUID(),"ALLOCATE","100.00"))).isInstanceOf(ResponseStatusException.class);assertThat(held()).isEqualByComparingTo("1000");
 }
 @Test void releaseCannotConsumeOtherHolds() {
  assertThatThrownBy(()->service.apply(command(UUID.randomUUID(),"RELEASE","100.00"))).isInstanceOf(ResponseStatusException.class);assertThat(held()).isEqualByComparingTo("1000");
 }
 @Test void outboxFailureRollsBackBalanceAndReservation() {
  jdbc.execute("ALTER TABLE app.OUTBOX_EVENT ADD CONSTRAINT test_reject_event CHECK(event_type='impossible') NOCHECK");
  try {assertThatThrownBy(()->service.apply(command(UUID.randomUUID(),"ALLOCATE","100.00"))).isInstanceOf(RuntimeException.class);assertThat(held()).isEqualByComparingTo("1000");assertThat(service.balances(account)).isEmpty();}
  finally {jdbc.execute("ALTER TABLE app.OUTBOX_EVENT DROP CONSTRAINT test_reject_event");}
 }
 @Test void concurrentRetriesReserveOnce() throws Exception {
  var executor=Executors.newFixedThreadPool(2);UUID id=UUID.randomUUID();
  try {var first=executor.submit(()->service.apply(command(id,"ALLOCATE","1000.00")));var second=executor.submit(()->service.apply(command(id,"ALLOCATE","1000.00")));first.get(10,TimeUnit.SECONDS);second.get(10,TimeUnit.SECONDS);assertThat(held()).isEqualByComparingTo("2000");}
  finally{executor.shutdownNow();}
 }
 @Test void concurrentSplitsCannotOverspend() throws Exception {
  var executor=Executors.newFixedThreadPool(2);
  Callable<Boolean> call=()->{try{service.apply(new SavingsCommand(UUID.randomUUID(),10L,account,"ALLOCATE",List.of(new SavingsCommand.Line(UUID.randomUUID(),new BigDecimal("9000.00"),new BigDecimal("10000")))));return true;}catch(ResponseStatusException ex){return false;}};
  try{var a=executor.submit(call);var b=executor.submit(call);assertThat(List.of(a.get(10,TimeUnit.SECONDS),b.get(10,TimeUnit.SECONDS))).containsExactlyInAnyOrder(true,false);assertThat(held()).isEqualByComparingTo("10000");}finally{executor.shutdownNow();}
 }
}
